const currencyCatalog = [
  { currency: 'EUR', name: 'Euro', flag: '🇪🇺' },
  { currency: 'USD', name: 'U.S. Dollar', flag: '🇺🇸' },
  { currency: 'GBP', name: 'British Pound', flag: '🇬🇧' },
  { currency: 'CAD', name: 'Canadian Dollar', flag: '🇨🇦' },
  { currency: 'CHF', name: 'Swiss Franc', flag: '🇨🇭' },
  { currency: 'CNY', name: 'Chinese Yuan', flag: '🇨🇳' },

  { currency: 'AED', name: 'UAE Dirham', flag: '🇦🇪' },
  { currency: 'AFN', name: 'AFN', flag: '🇦🇫' },
  { currency: 'ALL', name: 'Albanian Lek', flag: '🇦🇱' },
  { currency: 'AMD', name: 'Armenian Dram', flag: '🇦🇲' },
  { currency: 'ANG', name: 'Neth Antilles Guilder', flag: '🌐' },
  { currency: 'AOA', name: 'Angolan New Kwanza', flag: '🇦🇴' },
  { currency: 'ARS', name: 'Argentine Peso', flag: '🇦🇷' },
  { currency: 'AUD', name: 'Australian Dollar', flag: '🇦🇺' },
  { currency: 'AWG', name: 'Aruba Florin', flag: '🇦🇼' },
  { currency: 'AZN', name: 'AZN', flag: '🇦🇿' },
  { currency: 'BAM', name: 'Bosnian Marka', flag: '🇧🇦' },
  { currency: 'BBD', name: 'Barbados Dollar', flag: '🇧🇧' },
  { currency: 'BDT', name: 'Bangladesh Taka', flag: '🇧🇩' },
  { currency: 'BGN', name: 'Bulgarian Lev', flag: '🇧🇬' },
  { currency: 'BHD', name: 'Bahraini Dinar', flag: '🇧🇭' },
  { currency: 'BIF', name: 'Burundi Franc', flag: '🇧🇮' },
  { currency: 'BMD', name: 'Bermuda Dollar', flag: '🇧🇲' },
  { currency: 'BND', name: 'Brunei Dollar', flag: '🇧🇳' },
  { currency: 'BOB', name: 'Bolivian Boliviano', flag: '🇧🇴' },
  { currency: 'BRL', name: 'Brazilian Real', flag: '🇧🇷' },
  { currency: 'BSD', name: 'Bahamian Dollar', flag: '🇧🇸' },
  { currency: 'BTC', name: 'BTC', flag: '₿' },
  { currency: 'BTN', name: 'Bhutan Ngultrum', flag: '🇧🇹' },
  { currency: 'BWP', name: 'Botswana Pula', flag: '🇧🇼' },
  { currency: 'BYN', name: 'BYN', flag: '🇧🇾' },
  { currency: 'BZD', name: 'Belize Dollar', flag: '🇧🇿' },
  { currency: 'CDF', name: 'Congolese Franc', flag: '🇨🇩' },
  { currency: 'CLF', name: 'CLF', flag: '🌐' },
  { currency: 'CLP', name: 'Chilean Peso', flag: '🇨🇱' },
  { currency: 'CNH', name: 'CNH', flag: '🌐' },
  { currency: 'COP', name: 'Colombian Peso', flag: '🇨🇴' },
  { currency: 'CRC', name: 'Costa Rica Colon', flag: '🇨🇷' },
  { currency: 'CUP', name: 'Cuban Peso', flag: '🇨🇺' },
  { currency: 'CVE', name: 'Cape Verde Escudo', flag: '🇨🇻' },
  { currency: 'CZK', name: 'Czech Koruna', flag: '🇨🇿' },
  { currency: 'DJF', name: 'Djibouti Franc', flag: '🇩🇯' },
  { currency: 'DKK', name: 'Danish Krone', flag: '🇩🇰' },
  { currency: 'DOP', name: 'Dominican Peso', flag: '🇩🇴' },
  { currency: 'DZD', name: 'Algerian Dinar', flag: '🇩🇿' },
  { currency: 'EGP', name: 'Egyptian Pound', flag: '🇪🇬' },
  { currency: 'ERN', name: 'Eritrea Nakfa', flag: '🇪🇷' },
  { currency: 'ETB', name: 'Ethiopian Birr', flag: '🇪🇹' },
  { currency: 'FJD', name: 'Fiji Dollar', flag: '🇫🇯' },
  { currency: 'FKP', name: 'Falkland Islands Pound', flag: '🇫🇰' },
  { currency: 'GEL', name: 'Georgian Lari', flag: '🇬🇪' },
  { currency: 'GGP', name: 'Guernsey Pound', flag: '🌐' },
  { currency: 'GHS', name: 'GHS', flag: '🇬🇭' },
  { currency: 'GIP', name: 'Gibraltar Pound', flag: '🇬🇮' },
  { currency: 'GMD', name: 'Gambian Dalasi', flag: '🇬🇲' },
  { currency: 'INR', name: 'Indian Rupee', flag: '🇮🇳' },
  { currency: 'IQD', name: 'Iraqi Dinar', flag: '🇮🇶' },
  { currency: 'IRR', name: 'Iran Rial', flag: '🇮🇷' },
  { currency: 'ISK', name: 'Iceland Krona', flag: '🇮🇸' },
  { currency: 'JEP', name: 'Jersey Pound', flag: '🌐' },
  { currency: 'JMD', name: 'Jamaican Dollar', flag: '🇯🇲' },
  { currency: 'JOD', name: 'Jordanian Dinar', flag: '🇯🇴' },
  { currency: 'JPY', name: 'Japanese Yen', flag: '🇯🇵' },
  { currency: 'KES', name: 'Kenyan Shilling', flag: '🇰🇪' },
  { currency: 'KGS', name: 'Kyrgyzstan Som', flag: '🇰🇬' },
  { currency: 'KHR', name: 'Cambodia Riel', flag: '🇰🇭' },
  { currency: 'KMF', name: 'Comoros Franc', flag: '🇰🇲' },
  { currency: 'KPW', name: 'North Korean Won', flag: '🇰🇵' },
  { currency: 'KRW', name: 'Korean Won', flag: '🇰🇷' },
  { currency: 'KWD', name: 'Kuwaiti Dinar', flag: '🇰🇼' },
  { currency: 'KYD', name: 'Cayman Islands Dollar', flag: '🇰🇾' },
  { currency: 'KZT', name: 'Kazakhstan Tenge', flag: '🇰🇿' },
  { currency: 'LAK', name: 'Lao Kip', flag: '🇱🇦' },
  { currency: 'LBP', name: 'Lebanese Pound', flag: '🇱🇧' },
  { currency: 'LKR', name: 'Sri Lanka Rupee', flag: '🇱🇰' },
  { currency: 'LRD', name: 'Liberian Dollar', flag: '🇱🇷' },
  { currency: 'LSL', name: 'Lesotho Loti', flag: '🇱🇸' },
  { currency: 'LYD', name: 'Libyan Dinar', flag: '🇱🇾' },
  { currency: 'MAD', name: 'Moroccan Dirham', flag: '🇲🇦' },
  { currency: 'MDL', name: 'Moldovan Leu', flag: '🇲🇩' },
  { currency: 'MGA', name: 'MGA', flag: '🇲🇬' },
  { currency: 'MKD', name: 'Macedonian Denar', flag: '🇲🇰' },
  { currency: 'RUB', name: 'Russian Rouble', flag: '🇷🇺' },
  { currency: 'RWF', name: 'Rwanda Franc', flag: '🇷🇼' },
  { currency: 'SAR', name: 'Saudi Arabian Riyal', flag: '🇸🇦' },
  { currency: 'SBD', name: 'Solomon Islands Dollar', flag: '🇸🇧' },
  { currency: 'SCR', name: 'Seychelles Rupee', flag: '🇸🇨' },
  { currency: 'SDG', name: 'SDG', flag: '🇸🇩' },
  { currency: 'SEK', name: 'Swedish Krona', flag: '🇸🇪' },
  { currency: 'SGD', name: 'Singapore Dollar', flag: '🇸🇬' },
  { currency: 'SHP', name: 'St Helena Pound', flag: '🇸🇭' }
];

module.exports = {
  currencyCatalog,
};
